### ISSUE TITLE
Rolstoelkat is stom

### ISSUE THREAD

**Issue by DraakjeYoblama** [krokanjer/rolstoelkat#1]
verwijder deze website onmiddelijk

**Comment by krokanjer** [comment]
wat ben jij voor een Gore vieze kut hater wie denk je wel niet dat je bent
!!?? beetje jezelf verschuilen achter een gebruikersnaam draakjeyobama jij
vieze kut mogool rolstoelkat is de besten

verzonden vanaf mijn ipad

**Comment by heinheinhein** [comment]
wat krokanjer zei
